/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 ../public/Platform_car.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Platform_car.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.608, 0]} scale={[0.774, 1, 3.914]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Plane002_4.geometry} material={materials['Material.021']} />
        <group position={[0, -0.132, 0.734]} rotation={[0, 0, Math.PI]} scale={[-0.799, -1, -0.043]}>
          <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.005']} />
          <group position={[-0.013, -0.189, -3.017]} rotation={[0, 0, Math.PI / 2]} scale={[-1.317, -0.124, -7.779]}>
            <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-0.013, -0.189, 2.98]} rotation={[0, 0, Math.PI / 2]} scale={[-1.317, -0.124, -7.779]}>
            <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.004']} />
          </group>
        </group>
        <group position={[0, -0.132, -0.736]} rotation={[0, 0, Math.PI]} scale={[-0.799, -1, -0.043]}>
          <mesh geometry={nodes.Plane001.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.005']} />
          <group position={[-0.013, -0.189, -3.017]} rotation={[0, 0, Math.PI / 2]} scale={[-1.317, -0.124, -7.779]}>
            <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-0.013, -0.189, 2.98]} rotation={[0, 0, Math.PI / 2]} scale={[-1.317, -0.124, -7.779]}>
            <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Material.004']} />
          </group>
        </group>
        <group position={[0, 0.089, 0.491]} scale={[0.888, 1, 0.474]}>
          <mesh geometry={nodes.Plane003.geometry} material={materials['Material.019']} />
          <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.005']} />
        </group>
        <group position={[0, 0.089, -0.49]} scale={[0.888, 1, 0.474]}>
          <mesh geometry={nodes.Plane004.geometry} material={materials['Material.019']} />
          <mesh geometry={nodes.Plane004_1.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-0.036, -0.242, 1.029]} scale={[0.637, 0.624, 0.836]}>
          <mesh geometry={nodes.Cube003.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.012']} />
        </group>
        <group position={[-0.036, -0.242, -1.028]} rotation={[Math.PI, 0, Math.PI]} scale={[0.637, 0.624, 0.836]}>
          <mesh geometry={nodes.Cube001.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.012']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Platform_car.glb')
